### ISSUE TITLE
Question about 3D point

### ISSUE THREAD

**Issue by marcotchella** [amitt1236/Gaze_estimation#2]
First, thank you for this code and the article on Medium.
The question is how did get or calculate 3D model points in array  [**model_points**](https://github.com/amitt1236/Gaze_estimation/blob/4c5e14e3fe252ad1cb58ef32be210faf531279f5/gaze.py#L41) ?
The same for **[Eye_ball_center_right](https://github.com/amitt1236/Gaze_estimation/blob/4c5e14e3fe252ad1cb58ef32be210faf531279f5/gaze.py#L54)** and [**Eye_ball_center_left**](https://github.com/amitt1236/Gaze_estimation/blob/4c5e14e3fe252ad1cb58ef32be210faf531279f5/gaze.py#L55) .

**Comment by amitt1236** [comment]
You can look at https://github.com/amitt1236/Gaze_estimation/issues/1
Someone else already asked the same question :)

**Comment by marcotchella** [comment]
yes, i  see the [issue](https://github.com/amitt1236/Gaze_estimation/issues/1), but i couldn´t understand
