### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by Itamar651** [amitt1236/Gaze_estimation#3]
Hi, 
Thanks for this project.

I have some questions about your code:

On line 84 in the file gaze.py of calculating the value of the variable S and I saw that you assume that the distance from the camera is 10 because it is not possible to find it.
1. What units are these? (cm, inch)
2. I saw that there is a way to find the distance from the camera using opencv\mediapipe, if I will use the real distance should it improve the accuracy?

I understood that there is a 3D axis system that simulates the 3D world. On the screen the angle of the eye is shown in two dimensions and I am interested in finding out the angle of the eye in three dimensions
Picture:
![angleThatIWantToFind](https://github.com/amitt1236/Gaze_estimation/assets/110099794/f982e4a0-bbef-4f62-9a4e-e4dcb5390126)

3. Can you please explain to me how to find the angle of the eye in the 3D world?
(I want to use this and the distance from the screen to find the exact position of the eye)

Thanks for your time :)

**Comment by amitt1236** [comment]
Hi, 
It's an old project so I don't remember the small details. 

Calculating distance its a pretty easy task, it wasn't included to keep the code simple.
The code is pretty basic and  indeed can be improved.

Sorry I cant offer much help
